/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlujoDeBalanceRouteImport } from './routes/FlujoDeBalance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FromIdRouteImport } from './routes/From/$id'

const FlujoDeBalanceRoute = FlujoDeBalanceRouteImport.update({
  id: '/FlujoDeBalance',
  path: '/FlujoDeBalance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FromIdRoute = FromIdRouteImport.update({
  id: '/From/$id',
  path: '/From/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/FlujoDeBalance': typeof FlujoDeBalanceRoute
  '/From/$id': typeof FromIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/FlujoDeBalance': typeof FlujoDeBalanceRoute
  '/From/$id': typeof FromIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/FlujoDeBalance': typeof FlujoDeBalanceRoute
  '/From/$id': typeof FromIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/FlujoDeBalance' | '/From/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/FlujoDeBalance' | '/From/$id'
  id: '__root__' | '/' | '/FlujoDeBalance' | '/From/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlujoDeBalanceRoute: typeof FlujoDeBalanceRoute
  FromIdRoute: typeof FromIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/FlujoDeBalance': {
      id: '/FlujoDeBalance'
      path: '/FlujoDeBalance'
      fullPath: '/FlujoDeBalance'
      preLoaderRoute: typeof FlujoDeBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/From/$id': {
      id: '/From/$id'
      path: '/From/$id'
      fullPath: '/From/$id'
      preLoaderRoute: typeof FromIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlujoDeBalanceRoute: FlujoDeBalanceRoute,
  FromIdRoute: FromIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
